version: "3.9"
services:
  nginx:
    container_name: "nginx"
    build:
      # nginx directory를 root로 사용
      context: ./nginx
      # ./nginx/Dockerfile을 사용해서 build
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - node
  node:
    container_name: "node"
    build:
      # velog directory를 root로 사용
      context: ./src
      # ./velog/Dockerfile을 사용해서 build
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

    ### Mongodb Servers
  mongo-vrame:
    image: mongo
    container_name: mongo-vrame
    restart: always
    logging:
      options:
        max-size: 1g
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - TZ=Asia/Seoul
    ports:
      - 27017:27017
    expose:
      - 27017
