# docker-compose.yml
version: "3.9"

services:
  gitlab:
    image: "gitlab/gitlab-ce:latest"
    restart: always
    hostname: "gitlab.vrame.com"
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.vrame.com:3000'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
    ports:
      - "443:443"
      - "3000:80"
    volumes:
      - "./gitlab/config:/etc/gitlab"
      - "./gitlab/logs:/var/log/gitlab"
      - "./gitlab/data:/var/opt/gitlab"
      - "./gitlab/backup:/var/opt/gitlab/backups" # 백업 폴더 추가

  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    networks:
      - my-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.15
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - my-network
    depends_on:
      - fastapi

  fastapi:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fastapi
    command: gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:3000
    volumes:
      - ./:/var/www
    networks:
      my-network:
        aliases:
          - fastapi-app
    depends_on:
      - db

networks:
  my-network:

volumes:
  postgres_data:
